# Generated by Django 2.2.7 on 2020-06-15 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0002_song_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.FileField(default='Face.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default='', upload_to='audio'),
        ),
    ]
