# Generated by Django 2.2.7 on 2020-06-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200615_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.FileField(default='', upload_to='songimage'),
        ),
    ]
