# Generated by Django 2.2.7 on 2020-06-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.FileField(default='', upload_to='artistimage'),
        ),
    ]
